/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JOptionPane;

/**
 *
 * @author AzrixDya
 */
public class HomePage extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourse
     */
    public HomePage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        BarTop1 = new javax.swing.JPanel();
        BarTop = new javax.swing.JPanel();
        accountLogo = new javax.swing.JLabel();
        TextAdmin = new javax.swing.JLabel();
        ManageCourseBtn = new javax.swing.JButton();
        PercentageBtn = new javax.swing.JButton();
        ImportBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 600));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(47, 102, 144));

        Menu.setBackground(new java.awt.Color(22, 66, 91));

        BarTop1.setBackground(new java.awt.Color(58, 124, 165));
        BarTop1.setPreferredSize(new java.awt.Dimension(126, 2));

        javax.swing.GroupLayout BarTop1Layout = new javax.swing.GroupLayout(BarTop1);
        BarTop1.setLayout(BarTop1Layout);
        BarTop1Layout.setHorizontalGroup(
                BarTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        BarTop1Layout.setVerticalGroup(
                BarTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE));

        BarTop.setBackground(new java.awt.Color(58, 124, 165));
        BarTop.setPreferredSize(new java.awt.Dimension(126, 2));

        javax.swing.GroupLayout BarTopLayout = new javax.swing.GroupLayout(BarTop);
        BarTop.setLayout(BarTopLayout);
        BarTopLayout.setHorizontalGroup(
                BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        BarTopLayout.setVerticalGroup(
                BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE));

        accountLogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountLogo.setForeground(new java.awt.Color(255, 255, 255));
        accountLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-male-user-50.png"))); // NOI18N

        TextAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextAdmin.setForeground(new java.awt.Color(255, 255, 255));
        TextAdmin.setText("ADMIN");

        ManageCourseBtn.setBackground(new java.awt.Color(47, 102, 144));
        ManageCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageCourseBtn.setText("Manage Course");
        ManageCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCourseBtnActionPerformed(evt);
            }
        });

        PercentageBtn.setBackground(new java.awt.Color(47, 102, 144));
        PercentageBtn.setForeground(new java.awt.Color(255, 255, 255));
        PercentageBtn.setText("Percentage");
        PercentageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageBtnActionPerformed(evt);
            }
        });

        ImportBtn.setBackground(new java.awt.Color(47, 102, 144));
        ImportBtn.setForeground(new java.awt.Color(255, 255, 255));
        ImportBtn.setText("Import");
        ImportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(47, 102, 144));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-create-order-32.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-document-32.png"))); // NOI18N

        // jLabel13.setIcon(new
        // javax.swing.ImageIcon("D:\\Study\\UMT\\SEM2\\CSF3043_OOP\\Work\\Project\\Student-Grading-System\\asset\\icons8-download-32.png"));
        // // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-download-32.png")));

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BarTop1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(MenuLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel11)
                                                                .addComponent(jLabel12,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(jLabel13,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PercentageBtn,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ManageCourseBtn,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ImportBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(BarTop, javax.swing.GroupLayout.DEFAULT_SIZE, 152,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(accountLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextAdmin)
                                                .addGap(16, 16, 16))
                                        .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        MenuLayout.setVerticalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(TextAdmin))
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(accountLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BarTop, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout
                                                .createSequentialGroup()
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ManageCourseBtn)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PercentageBtn))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ImportBtn)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BarTop1, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(logoutBtn)
                                .addGap(29, 29, 29)));

        accountLogo.getAccessibleContext().setAccessibleName("Logo");

        jLabel1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("WELCOME TO STUDENT GRADING SYSTEM");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Step to using Student Grading System");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1. Enter manage course | To create a course and assign quantity of task");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2. Enter Percentage | To assign percentage for each task that has been assign");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("3. Enter Import | To import list of student and student mark for each course");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("List Task For Each Module ");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Module 1 | Quiz, Assignment, Test, Final Exam");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Module 2 | Quiz, Assignment, Test, Practical Test, Final Exam");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Module 3 | Quiz, Assignment, Test, Final Exam");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Module 5 | Quiz, Assignment, Test, Video Assignment, Final Exam");

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Module 4 | Quiz, Assignment, Test, Final Exam");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(224, 224, 224)
                                                .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(jPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel6)
                                                        .addComponent(jLabel7)
                                                        .addComponent(jLabel8)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel10)
                                                        .addComponent(jLabel14))))
                                .addContainerGap(271, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jLabel1)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(106, 106, 106)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addContainerGap(33, Short.MAX_VALUE))
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        setSize(new java.awt.Dimension(1060, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage loginFrame = new LoginPage();
        loginFrame.setVisible(true);
    }// GEN-LAST:event_logoutBtnActionPerformed

    private void ManageCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ManageCourseBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        ManageCourse frame = new ManageCourse();
        frame.setVisible(true);
    }// GEN-LAST:event_ManageCourseBtnActionPerformed

    private void PercentageBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PercentageBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please Go to Manage Course First!");
    }// GEN-LAST:event_PercentageBtnActionPerformed

    private void ImportBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ImportBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "Please Go to Manage Course First!");
    }// GEN-LAST:event_ImportBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    // MAIN RUN
    // public static void main(String args[]) {
    // /* Set the Nimbus look and feel */
    // //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code
    // (optional) ">
    // /* If Nimbus (introduced in Java SE 6) is not available, stay with the
    // default look and feel.
    // * For details see
    // http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
    // */
    // try {
    // for (javax.swing.UIManager.LookAndFeelInfo info :
    // javax.swing.UIManager.getInstalledLookAndFeels()) {
    // if ("Nimbus".equals(info.getName())) {
    // javax.swing.UIManager.setLookAndFeel(info.getClassName());
    // break;
    // }
    // }
    // } catch (ClassNotFoundException ex) {
    // java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (InstantiationException ex) {
    // java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (IllegalAccessException ex) {
    // java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // } catch (javax.swing.UnsupportedLookAndFeelException ex) {
    // java.util.logging.Logger.getLogger(HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
    // null, ex);
    // }
    // //</editor-fold>
    // //</editor-fold>

    // /* Create and display the form */
    // java.awt.EventQueue.invokeLater(new Runnable() {
    // public void run() {
    // new HomePage().setVisible(true);
    // }
    // });
    // }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarTop;
    private javax.swing.JPanel BarTop1;
    private javax.swing.JButton ImportBtn;
    private javax.swing.JButton ManageCourseBtn;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton PercentageBtn;
    private javax.swing.JLabel TextAdmin;
    private javax.swing.JLabel accountLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutBtn;
    // End of variables declaration//GEN-END:variables
}
