
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import javax.swing.JOptionPane;

import Course.*;

/**
 *
 * @author AzrixDya
 */
public class Percentage extends javax.swing.JFrame {

    /**
     * Creates new form ManageCourse
     */
    String hasAssign[] = new String[] {
            "Percentage : Null",
            "Percentage : Null",
            "Percentage : Null",
            "Percentage : Null",
            "Percentage : Null",
            "Percentage : Null"
    };
    private Course[] CourseInfo;

    public Percentage(Course[] CourseInfo) {
        this.CourseInfo = CourseInfo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Menu = new javax.swing.JPanel();
        BarTop1 = new javax.swing.JPanel();
        BarTop = new javax.swing.JPanel();
        accountLogo = new javax.swing.JLabel();
        TextAdmin = new javax.swing.JLabel();
        ManageCourseBtn = new javax.swing.JButton();
        PercentageBtn = new javax.swing.JButton();
        ImportBtn = new javax.swing.JButton();
        logoutBtn = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Module1Btn1 = new javax.swing.JButton();
        LabelModule1 = new javax.swing.JLabel();
        Module1Btn = new javax.swing.JButton();
        LabelModule2 = new javax.swing.JLabel();
        Module1Btn2 = new javax.swing.JButton();
        LabelModule3 = new javax.swing.JLabel();
        Module1Btn3 = new javax.swing.JButton();
        LabelModule4 = new javax.swing.JLabel();
        Module1Btn4 = new javax.swing.JButton();
        LabelModule5 = new javax.swing.JLabel();
        BarTop2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(47, 102, 144));

        Menu.setBackground(new java.awt.Color(22, 66, 91));

        BarTop1.setBackground(new java.awt.Color(58, 124, 165));
        BarTop1.setPreferredSize(new java.awt.Dimension(126, 2));

        javax.swing.GroupLayout BarTop1Layout = new javax.swing.GroupLayout(BarTop1);
        BarTop1.setLayout(BarTop1Layout);
        BarTop1Layout.setHorizontalGroup(
                BarTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        BarTop1Layout.setVerticalGroup(
                BarTop1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE));

        BarTop.setBackground(new java.awt.Color(58, 124, 165));
        BarTop.setPreferredSize(new java.awt.Dimension(126, 2));

        javax.swing.GroupLayout BarTopLayout = new javax.swing.GroupLayout(BarTop);
        BarTop.setLayout(BarTopLayout);
        BarTopLayout.setHorizontalGroup(
                BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        BarTopLayout.setVerticalGroup(
                BarTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE));

        accountLogo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        accountLogo.setForeground(new java.awt.Color(255, 255, 255));
        accountLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-male-user-50.png"))); // NOI18N

        TextAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TextAdmin.setForeground(new java.awt.Color(255, 255, 255));
        TextAdmin.setText("ADMIN");

        ManageCourseBtn.setBackground(new java.awt.Color(47, 102, 144));
        ManageCourseBtn.setForeground(new java.awt.Color(255, 255, 255));
        ManageCourseBtn.setText("Manage Course");
        ManageCourseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageCourseBtnActionPerformed(evt);
            }
        });

        PercentageBtn.setBackground(new java.awt.Color(47, 102, 144));
        PercentageBtn.setForeground(new java.awt.Color(255, 255, 255));
        PercentageBtn.setText("Percentage");
        PercentageBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PercentageBtnActionPerformed(evt);
            }
        });

        ImportBtn.setBackground(new java.awt.Color(47, 102, 144));
        ImportBtn.setForeground(new java.awt.Color(255, 255, 255));
        ImportBtn.setText("Import");
        ImportBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ImportBtnActionPerformed(evt);
            }
        });

        logoutBtn.setBackground(new java.awt.Color(47, 102, 144));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setText("Log Out");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/assets/icons8-create-order-32.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(
               getClass().getResource("/assets/icons8-document-32.png"))); // NOI18N

        jLabel13.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/assets/icons8-download-32.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(BarTop1, javax.swing.GroupLayout.Alignment.TRAILING,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(MenuLayout
                                                                .createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(jLabel11)
                                                                .addComponent(jLabel12,
                                                                        javax.swing.GroupLayout.Alignment.TRAILING))
                                                        .addComponent(jLabel13,
                                                                javax.swing.GroupLayout.Alignment.TRAILING))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(PercentageBtn,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ManageCourseBtn,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ImportBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addComponent(BarTop, javax.swing.GroupLayout.DEFAULT_SIZE, 154,
                                                Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout
                                                .createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(accountLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TextAdmin)
                                                .addGap(16, 16, 16))
                                        .addComponent(logoutBtn, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        MenuLayout.setVerticalGroup(
                MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(MenuLayout.createSequentialGroup()
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addGap(22, 22, 22)
                                                .addComponent(TextAdmin))
                                        .addGroup(MenuLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(accountLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BarTop, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MenuLayout
                                                .createSequentialGroup()
                                                .addGroup(MenuLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(ManageCourseBtn)
                                                        .addComponent(jLabel11))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(PercentageBtn))
                                        .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(ImportBtn)
                                        .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 233,
                                        Short.MAX_VALUE)
                                .addComponent(BarTop1, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(logoutBtn)
                                .addGap(29, 29, 29)));

        accountLogo.getAccessibleContext().setAccessibleName("Logo");

        jPanel2.setBackground(new java.awt.Color(58, 124, 165));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ASSIGN PERCENTAGE");

        if (CourseInfo[0] == null || CourseInfo[0].getCourseName() == null) {
            Module1Btn1.setText("Module 1");
        } else {
            Module1Btn1.setText(CourseInfo[0].getCourseName());
        }
        Module1Btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module1Btn1ActionPerformed(evt);
            }
        });

        LabelModule1.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        LabelModule1.setForeground(new java.awt.Color(255, 255, 255));
        LabelModule1.setText(hasAssign[0]);
        if (CourseInfo[1] == null || CourseInfo[1].getCourseName() == null) {
            Module1Btn.setText("Module 2");
        } else {
            Module1Btn.setText(CourseInfo[1].getCourseName());
        }
        Module1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module1BtnActionPerformed(evt);
            }
        });

        LabelModule2.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        LabelModule2.setForeground(new java.awt.Color(255, 255, 255));
        LabelModule2.setText(hasAssign[1]);

        if (CourseInfo[2] == null || CourseInfo[2].getCourseName() == null) {
            Module1Btn2.setText("Module 3");
        } else {
            Module1Btn2.setText(CourseInfo[2].getCourseName());
        }

        Module1Btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module1Btn2ActionPerformed(evt);
            }
        });

        LabelModule3.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        LabelModule3.setForeground(new java.awt.Color(255, 255, 255));
        LabelModule3.setText(hasAssign[2]);

        if (CourseInfo[3] == null || CourseInfo[3].getCourseName() == null) {
            Module1Btn3.setText("Module 4");
        } else {
            Module1Btn3.setText(CourseInfo[3].getCourseName());
        }
        Module1Btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module1Btn3ActionPerformed(evt);
            }
        });

        LabelModule4.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        LabelModule4.setForeground(new java.awt.Color(255, 255, 255));
        LabelModule4.setText(hasAssign[3]);

        if (CourseInfo[4] == null || CourseInfo[4].getCourseName() == null) {
            Module1Btn4.setText("Module 5");
        } else {
            Module1Btn4.setText(CourseInfo[4].getCourseName());
        }
        Module1Btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Module1Btn4ActionPerformed(evt);
            }
        });

        LabelModule5.setFont(new java.awt.Font("Eras Medium ITC", 1, 12)); // NOI18N
        LabelModule5.setForeground(new java.awt.Color(255, 255, 255));
        LabelModule5.setText(hasAssign[4]);

        BarTop2.setBackground(new java.awt.Color(47, 102, 144));
        BarTop2.setPreferredSize(new java.awt.Dimension(126, 2));

        javax.swing.GroupLayout BarTop2Layout = new javax.swing.GroupLayout(BarTop2);
        BarTop2.setLayout(BarTop2Layout);
        BarTop2Layout.setHorizontalGroup(
                BarTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE));
        BarTop2Layout.setVerticalGroup(
                BarTop2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 3, Short.MAX_VALUE));

        jLabel2.setBackground(new java.awt.Color(153, 153, 153));
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Assign percentage task for each module");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(BarTop2, javax.swing.GroupLayout.DEFAULT_SIZE, 844,
                                                        Short.MAX_VALUE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(28, 28, 28)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel2)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jLabel1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        345,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGap(30, 30, 30)
                                                                .addGroup(jPanel2Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Module1Btn4,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        132,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(LabelModule5))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Module1Btn2,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        132,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(LabelModule3))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Module1Btn,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        132,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(LabelModule2))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Module1Btn3,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        132,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(LabelModule4))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(Module1Btn1,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                        132,
                                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addComponent(LabelModule1)))))
                                                .addGap(0, 471, Short.MAX_VALUE)))
                                .addContainerGap()));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BarTop2, javax.swing.GroupLayout.PREFERRED_SIZE, 3,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Module1Btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModule1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Module1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModule2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Module1Btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModule3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Module1Btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModule4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(Module1Btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LabelModule5))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        setSize(new java.awt.Dimension(1060, 525));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_logoutBtnActionPerformed
        // TODO add your handling code here:
        dispose();
        LoginPage loginFrame = new LoginPage();
        loginFrame.setVisible(true);
    }// GEN-LAST:event_logoutBtnActionPerformed

    private void ManageCourseBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ManageCourseBtnActionPerformed

        dispose();
        ManageCourse frame = new ManageCourse(CourseInfo);
        frame.setVisible(true);

        // If NO_OPTION or CLOSED_OPTION, do nothing and return to the current frame
    }// GEN-LAST:event_ManageCourseBtnActionPerformed

    private void PercentageBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PercentageBtnActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PercentageBtnActionPerformed

    private void ImportBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ImportBtnActionPerformed
        // TODO add your handling code here:
        String filePath = JOptionPane.showInputDialog(this,
                "Please enter the Student List file path:",
                "Import File",
                JOptionPane.PLAIN_MESSAGE);

        // Check if the user entered a file path
        if (filePath != null && !filePath.trim().isEmpty()) {
            // User entered a file path, you can now use this file path for your logic
            // Example: Print the file path
            System.out.println("File path entered: " + filePath);
            Import frame = new Import(filePath, CourseInfo);
            frame.setVisible(true);
            dispose();

        } else {
            // User did not enter a valid file path (they might have canceled or left it
            // blank)
            System.out.println("No file path entered or operation was canceled.");
        }
    }// GEN-LAST:event_ImportBtnActionPerformed

    private void Module1Btn1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Module1Btn1ActionPerformed
        // TODO add your handling code here:
        if (CourseInfo[0] instanceof Subject1) {
            Subject1 info = (Subject1) CourseInfo[0];
            info.assignPercentage();

            hasAssign[0] = "Percentage : COMPLETE";
            LabelModule1.setText(hasAssign[0]);
            LabelModule1.revalidate();
            LabelModule1.repaint();

        } else {
            JOptionPane.showMessageDialog(null, "You Not Assign This Course");
        }
    }// GEN-LAST:event_Module1Btn1ActionPerformed

    private void Module1BtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Module1BtnActionPerformed
        // TODO add your handling code here:
        if (CourseInfo[1] instanceof Subject2) {
            Subject2 info = (Subject2) CourseInfo[1];
            info.assignPercentage();

            hasAssign[1] = "Percentage : COMPLETE";
            LabelModule2.setText(hasAssign[1]);
            LabelModule2.revalidate();
            LabelModule2.repaint();

        } else {
            JOptionPane.showMessageDialog(null, "You Not Assign This Course");
        }
    }// GEN-LAST:event_Module1BtnActionPerformed

    private void Module1Btn2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Module1Btn2ActionPerformed
        // TODO add your handling code here:
        if (CourseInfo[2] instanceof Subject3) {
            Subject3 info = (Subject3) CourseInfo[2];
            info.assignPercentage();

            hasAssign[2] = "Percentage : COMPLETE";
            LabelModule3.setText(hasAssign[2]);
            LabelModule3.revalidate();
            LabelModule3.repaint();

        } else {
            JOptionPane.showMessageDialog(null, "You Not Assign This Course");
        }
    }// GEN-LAST:event_Module1Btn2ActionPerformed

    private void Module1Btn3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Module1Btn3ActionPerformed
        // TODO add your handling code here:
        if (CourseInfo[3] instanceof Subject4) {
            Subject4 info = (Subject4) CourseInfo[3];
            info.assignPercentage();

            hasAssign[3] = "Percentage : COMPLETE";
            LabelModule4.setText(hasAssign[3]);
            LabelModule4.revalidate();
            LabelModule4.repaint();

        } else {
            JOptionPane.showMessageDialog(null, "You Not Assign This Course");
        }
    }// GEN-LAST:event_Module1Btn3ActionPerformed

    private void Module1Btn4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_Module1Btn4ActionPerformed
        // TODO add your handling code here:
        if (CourseInfo[4] instanceof Subject5) {
            Subject5 info = (Subject5) CourseInfo[4];
            info.assignPercentage();

            hasAssign[4] = "Percentage : COMPLETE";
            LabelModule5.setText(hasAssign[4]);
            LabelModule5.revalidate();
            LabelModule5.repaint();

        } else {
            JOptionPane.showMessageDialog(null, "You Not Assign This Course");
        }
    }// GEN-LAST:event_Module1Btn4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarTop;
    private javax.swing.JPanel BarTop1;
    private javax.swing.JPanel BarTop2;
    private javax.swing.JButton ImportBtn;
    private javax.swing.JLabel LabelModule1;
    private javax.swing.JLabel LabelModule2;
    private javax.swing.JLabel LabelModule3;
    private javax.swing.JLabel LabelModule4;
    private javax.swing.JLabel LabelModule5;
    private javax.swing.JButton ManageCourseBtn;
    private javax.swing.JPanel Menu;
    private javax.swing.JButton Module1Btn;
    private javax.swing.JButton Module1Btn1;
    private javax.swing.JButton Module1Btn2;
    private javax.swing.JButton Module1Btn3;
    private javax.swing.JButton Module1Btn4;
    private javax.swing.JButton PercentageBtn;
    private javax.swing.JLabel TextAdmin;
    private javax.swing.JLabel accountLogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton logoutBtn;
    // End of variables declaration//GEN-END:variables
}
